### ISSUE TITLE
You've used my code without permission

### ISSUE THREAD

**Issue by KK4OXJ** [myano/lmddgtfy#7]
Hi Michael, 

I'm the creator of https://github.com/LMDDGTFY. 
I'm honored that you like my work enough use it on your own project, but I'd like to request that you revert your code back to what it was before June 15, 2015, as you have not asked permission to use my code, and the code you copied was an early release not yet fully working. 

P.S.

I believe DuckDuckGo requires you to have some form of an "unofficial site" notice. You removed this when you copied my code. When creating my project, I got permission from DuckDuckGo to use the mascot (Dax) and name on the site: 

> [...] For now, our only request is that you signify "unofficial" near the name/logo

**Comment by myano** [comment]
Hello Zeke Y,

I apologize for misusing your code. I must have been working on multiple projects that night and I thought I remember seeing a LICENSE file in the https://github.com/lmddgtfy project. It appears that according to mine and your git commit history that, that isn't true. I thought at most I had forgot to upload the LICENSE file when publishing your code.

Anyways, I've reverted the changes per your wish as without a license file it would be unauthorized use of your code, and I do apologize for that. I hope we can work out an agreement in the future so your code can be reached by [many others](https://lmddgtfy.net/traffic.html) on https://lmddgtfy.net/

---

Regrading the P.S., the reason that was removed is because even though DuckDuckGo doesn't officially operate, run, nor maintain lmddgtfy.net, it has been given the blessing of having permission to use the logos and operate in its manner from several sources:

* The supposed "used with permission" from the original project hosted by mikejs.
* The listing of lmddgtfy.net on duck.co's community site, https://duck.co/help/add-ons/lmddgtfy
* and a personal e-mail correspondence with Weinberg and myself about making changes to Apache logs to increase privacy for lmddgtfy.net.

If DuckDuckGo would officially like https://lmddgtfy.net/ to add a "unofficial site" I'd be more than happy to add it.

**Comment by KK4OXJ** [comment]
@myano Thanks for reverting, and doing it so quickly :)

re: 

> I hope we can work out an agreement in the future so your code can be reached by [many others](https://lmddgtfy.net/traffic.html) on https://lmddgtfy.net/

I'm sure we can work out some sort of deal, but I'd kind of like more attribution than just "created by Zeke Y" if I made the whole entire UI. I don't really know yet how I'll do it. I think I'll look into some licenses soon and decide on one, then go license my code. 

-----

If DDG is fine with you not having the notice, I don't mind at all either. I just thought maybe you didn't realize they wanted you to have the unofficial site notice :)

**Comment by KK4OXJ** [comment]
@myano If you'd like to help me with the project, I've created [a to do list](https://github.com/LMDDGTFY/lmddgtfy.github.io/issues/2) of the stuff that needs to happen before it's released.  
Sorry I haven't looked at licenses yet, I'm going to try and do that soon.

**Comment by KK4OXJ** [comment]
@myano Could you take a look at what I've got right now? The footer just says "copyright 2015 LMDDGTFY", but the word LMDDGTFY links to /about.html, which says that I made it, we both maintain it (since I'm planning on helping out with the code in the future, but we could change that bit if you want), and that you pay for the hosting and stuff.

**Comment by KK4OXJ** [comment]
@myano I've added a license file now, using the [MIT license](http://opensource.org/licenses/MIT). All good?

**Comment by myano** [comment]
@KK4OXJ Howdy, I'm sorry I haven't responded yet. I'm willing to have whatever attribution you'd like on the page you'd like as long as I can point out that it is hosted and also maintained by me as well. Which sounds like it will work for the two of us.

I looked at the to do list and it seems the last issue is the Apple devices problem. I don't own any mobile Apple devices and can't really help out with that, but I'm willing to help with other things that come up as time goes along.

The MIT License works for me.

Are you ready to have the code live on https://lmddgtfy.net/ ? If so would you like to submit a pull request against my project to preserve the git history?

(Also, when moving it over to https://lmddgtfy.net/ as I mentioned early I'll remove the "unofficial site" notice because of the points mentioned previously.)

**Comment by KK4OXJ** [comment]
@myano 

> Are you ready to have the code live on https://lmddgtfy.net/ ?

Your call. The site is functional on Apple devices, but it doesn't look right on them yet. Do you want to push it live now, or would you like to wait until we fix [the two problems](https://github.com/LMDDGTFY/lmddgtfy.github.io/issues/2) on Apple devices left?

**Comment by KK4OXJ** [comment]
PR submitted!

**Comment by myano** [comment]
@KK4OXJ Awesome, thank you very much.

I made a few small tweaks that you can see in the git history. Mostly just cleaning up a few things. Nothing major was changed.
